import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Sep 15, 2011, 12:31:59 AM
 */

/**
 *
 * @author Kshitij
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JFrame();
        openlogin = new javax.swing.JButton();
        opensignup = new javax.swing.JButton();
        opensearch = new javax.swing.JButton();
        opendatabase = new javax.swing.JButton();
        getuserinfo = new javax.swing.JButton();
        mainexit = new javax.swing.JButton();
        mainloginname = new javax.swing.JLabel();
        mainexit1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        loginpage = new javax.swing.JFrame();
        getusername = new javax.swing.JTextField();
        rememberme = new javax.swing.JCheckBox();
        buttonforgotpass = new javax.swing.JButton();
        login = new javax.swing.JButton();
        getpassword = new javax.swing.JPasswordField();
        exitlogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        searchpage = new javax.swing.JFrame();
        searchuser = new javax.swing.JLabel();
        searchpanel = new javax.swing.JPanel();
        searchbypanel = new javax.swing.JPanel();
        s1 = new javax.swing.JRadioButton();
        s3 = new javax.swing.JRadioButton();
        s4 = new javax.swing.JRadioButton();
        s2 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        getsearchdata = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        c1 = new javax.swing.JRadioButton();
        c2 = new javax.swing.JRadioButton();
        c3 = new javax.swing.JRadioButton();
        c4 = new javax.swing.JRadioButton();
        searchresult = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        getbookcode = new javax.swing.JTextField();
        getinfo1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        showauthor = new javax.swing.JLabel();
        showtitle = new javax.swing.JLabel();
        borrow = new javax.swing.JButton();
        exitsearch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        signuppage = new javax.swing.JFrame();
        signup = new javax.swing.JButton();
        getuser = new javax.swing.JTextField();
        getpass = new javax.swing.JPasswordField();
        signupexit = new javax.swing.JButton();
        getemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        udpage = new javax.swing.JFrame();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jt1 = new javax.swing.JTextField();
        jt2 = new javax.swing.JTextField();
        jt4 = new javax.swing.JTextField();
        jt3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        c11 = new javax.swing.JRadioButton();
        c12 = new javax.swing.JRadioButton();
        c13 = new javax.swing.JRadioButton();
        c14 = new javax.swing.JRadioButton();
        add = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        getcode = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        changestatus = new javax.swing.JButton();
        getinfo = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jcmb1 = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jcmb2 = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        btf = new javax.swing.JTextField();
        jcmb3 = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        ctf = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jcmb4 = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        dtf = new javax.swing.JTextField();
        modify = new javax.swing.JButton();
        signupexit1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        forgotpassword = new javax.swing.JFrame();
        jTextField5 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        getforgottenpass = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jOptionPane1 = new javax.swing.JOptionPane();
        jOptionPane2 = new javax.swing.JOptionPane();
        statusoption = new javax.swing.JFrame();
        jLabel21 = new javax.swing.JLabel();
        z1 = new javax.swing.JRadioButton();
        z3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        buttonGroup3 = new javax.swing.ButtonGroup();
        userinfo = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        continuebutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        main.setLocationByPlatform(true);
        main.setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        main.setMinimumSize(new java.awt.Dimension(681, 701));
        main.setUndecorated(true);
        main.setResizable(false);
        main.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        openlogin.setBackground(new java.awt.Color(255, 255, 255));
        openlogin.setForeground(new java.awt.Color(255, 255, 255));
        openlogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        openlogin.setContentAreaFilled(false);
        openlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openloginActionPerformed(evt);
            }
        });
        main.getContentPane().add(openlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 170, 50));

        opensignup.setBackground(new java.awt.Color(255, 255, 255));
        opensignup.setForeground(new java.awt.Color(255, 255, 255));
        opensignup.setBorderPainted(false);
        opensignup.setContentAreaFilled(false);
        opensignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opensignupActionPerformed(evt);
            }
        });
        main.getContentPane().add(opensignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 153, 210, 50));

        opensearch.setBackground(new java.awt.Color(255, 255, 255));
        opensearch.setForeground(new java.awt.Color(255, 255, 255));
        opensearch.setBorderPainted(false);
        opensearch.setContentAreaFilled(false);
        opensearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opensearchActionPerformed(evt);
            }
        });
        main.getContentPane().add(opensearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 210, 50));

        opendatabase.setBackground(new java.awt.Color(255, 255, 255));
        opendatabase.setForeground(new java.awt.Color(255, 255, 255));
        opendatabase.setBorderPainted(false);
        opendatabase.setContentAreaFilled(false);
        opendatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opendatabaseActionPerformed(evt);
            }
        });
        main.getContentPane().add(opendatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 450, 40));

        getuserinfo.setBackground(new java.awt.Color(255, 255, 255));
        getuserinfo.setForeground(new java.awt.Color(255, 255, 255));
        getuserinfo.setBorderPainted(false);
        getuserinfo.setContentAreaFilled(false);
        getuserinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getuserinfoActionPerformed(evt);
            }
        });
        main.getContentPane().add(getuserinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 330, 40));

        mainexit.setBorderPainted(false);
        mainexit.setContentAreaFilled(false);
        mainexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainexitActionPerformed(evt);
            }
        });
        main.getContentPane().add(mainexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 650, 120, 50));

        mainloginname.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        mainloginname.setForeground(new java.awt.Color(255, 255, 255));
        main.getContentPane().add(mainloginname, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 150, 20));

        mainexit1.setBorderPainted(false);
        mainexit1.setContentAreaFilled(false);
        mainexit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainexit1ActionPerformed(evt);
            }
        });
        main.getContentPane().add(mainexit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 120, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/j0409270.jpg"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        main.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, -1, -1));

        jLabel32.setText("kkadane");
        main.getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, -1, -1));

        loginpage.setBackground(new java.awt.Color(255, 255, 255));
        loginpage.setLocationByPlatform(true);
        loginpage.setMinimumSize(new java.awt.Dimension(426, 323));
        loginpage.setUndecorated(true);
        loginpage.setResizable(false);
        loginpage.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getusername.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getusername.setForeground(new java.awt.Color(255, 255, 255));
        getusername.setBorder(null);
        getusername.setCaretColor(new java.awt.Color(255, 255, 255));
        getusername.setOpaque(false);
        loginpage.getContentPane().add(getusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 210, 30));

        rememberme.setOpaque(false);
        loginpage.getContentPane().add(rememberme, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 220, 20, 20));

        buttonforgotpass.setBackground(new java.awt.Color(255, 255, 255));
        buttonforgotpass.setForeground(new java.awt.Color(255, 255, 255));
        buttonforgotpass.setBorderPainted(false);
        buttonforgotpass.setContentAreaFilled(false);
        buttonforgotpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonforgotpassActionPerformed(evt);
            }
        });
        loginpage.getContentPane().add(buttonforgotpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 223, 90, 20));

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setBorderPainted(false);
        login.setContentAreaFilled(false);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        loginpage.getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 100, 40));

        getpassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getpassword.setForeground(new java.awt.Color(255, 255, 255));
        getpassword.setBorder(null);
        getpassword.setCaretColor(new java.awt.Color(255, 255, 255));
        getpassword.setOpaque(false);
        loginpage.getContentPane().add(getpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 210, 30));

        exitlogin.setBorderPainted(false);
        exitlogin.setContentAreaFilled(false);
        exitlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitloginActionPerformed(evt);
            }
        });
        loginpage.getContentPane().add(exitlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 293, 60, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.png.jpg"))); // NOI18N
        jLabel3.setAlignmentX(20.0F);
        jLabel3.setAlignmentY(10.5F);
        jLabel3.setMinimumSize(new java.awt.Dimension(426, 324));
        loginpage.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        searchpage.setBackground(new java.awt.Color(255, 255, 255));
        searchpage.setLocationByPlatform(true);
        searchpage.setMinimumSize(new java.awt.Dimension(783, 458));
        searchpage.setUndecorated(true);
        searchpage.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchuser.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        searchuser.setForeground(new java.awt.Color(255, 255, 255));
        searchpage.getContentPane().add(searchuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 180, 30));

        searchpanel.setBackground(new java.awt.Color(255, 255, 255));
        searchpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        searchpanel.setForeground(new java.awt.Color(255, 255, 255));
        searchpanel.setOpaque(false);
        searchpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchbypanel.setBackground(new java.awt.Color(255, 255, 255));
        searchbypanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search By", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        searchbypanel.setOpaque(false);
        searchbypanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(s1);
        s1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        s1.setForeground(new java.awt.Color(255, 255, 255));
        s1.setText("Author/Editor");
        s1.setOpaque(false);
        searchbypanel.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        buttonGroup1.add(s3);
        s3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        s3.setForeground(new java.awt.Color(255, 255, 255));
        s3.setText("Publication");
        s3.setOpaque(false);
        searchbypanel.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        buttonGroup1.add(s4);
        s4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        s4.setForeground(new java.awt.Color(255, 255, 255));
        s4.setText("Serial Code");
        s4.setOpaque(false);
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });
        searchbypanel.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        buttonGroup1.add(s2);
        s2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        s2.setForeground(new java.awt.Color(255, 255, 255));
        s2.setText("Title");
        s2.setOpaque(false);
        searchbypanel.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        searchpanel.add(searchbypanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 127, 120));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getsearchdata.setToolTipText("");
        jPanel4.add(getsearchdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 118, -1));

        search.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel4.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 118, 39));

        searchpanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 140, 120));

        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Author/Editor", "Title", "Publication", "Serial Code", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t1.setOpaque(false);
        jScrollPane1.setViewportView(t1);

        searchpanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 460, 88));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Category", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup2.add(c1);
        c1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c1.setForeground(new java.awt.Color(255, 255, 255));
        c1.setText("Novel");
        c1.setOpaque(false);
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel3.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        buttonGroup2.add(c2);
        c2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c2.setForeground(new java.awt.Color(255, 255, 255));
        c2.setText("Magazine");
        c2.setOpaque(false);
        jPanel3.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        buttonGroup2.add(c3);
        c3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c3.setForeground(new java.awt.Color(255, 255, 255));
        c3.setText("Newspaper");
        c3.setOpaque(false);
        jPanel3.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        buttonGroup2.add(c4);
        c4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c4.setForeground(new java.awt.Color(255, 255, 255));
        c4.setText("Comics");
        c4.setOpaque(false);
        jPanel3.add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        searchpanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 120));

        searchresult.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        searchresult.setForeground(new java.awt.Color(255, 255, 255));
        searchpanel.add(searchresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 170, 20));

        searchpage.getContentPane().add(searchpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 490, 290));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Request/Borrow", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Serial", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(getbookcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, 20));

        getinfo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getinfo1.setText("Get Info");
        getinfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getinfo1ActionPerformed(evt);
            }
        });
        jPanel6.add(getinfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 150, 20));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 170, 90));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Book Description Here", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel7.setOpaque(false);

        showauthor.setForeground(new java.awt.Color(255, 255, 255));
        showauthor.setText("              Author Here");

        showtitle.setForeground(new java.awt.Color(255, 255, 255));
        showtitle.setText("                Title Here");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showtitle, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(showauthor, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(showtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showauthor)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, 90));

        borrow.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        borrow.setText("BORROW");
        borrow.setEnabled(false);
        borrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowActionPerformed(evt);
            }
        });
        jPanel5.add(borrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 150, 30));

        searchpage.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 480, 170));

        exitsearch.setBorder(null);
        exitsearch.setBorderPainted(false);
        exitsearch.setContentAreaFilled(false);
        exitsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitsearchActionPerformed(evt);
            }
        });
        searchpage.getContentPane().add(exitsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 90, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/11318906-seo.jpg"))); // NOI18N
        jLabel4.setAlignmentX(10.0F);
        searchpage.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 460));

        signuppage.setLocationByPlatform(true);
        signuppage.setMinimumSize(new java.awt.Dimension(951, 430));
        signuppage.setUndecorated(true);
        signuppage.setResizable(false);
        signuppage.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signup.setBackground(new java.awt.Color(255, 255, 255));
        signup.setBorder(null);
        signup.setContentAreaFilled(false);
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        signuppage.getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 210, 60));

        getuser.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getuser.setBorder(null);
        getuser.setOpaque(false);
        getuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getuserActionPerformed(evt);
            }
        });
        signuppage.getContentPane().add(getuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 260, 280, 30));

        getpass.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getpass.setBorder(null);
        getpass.setOpaque(false);
        signuppage.getContentPane().add(getpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 280, 30));

        signupexit.setBorder(null);
        signupexit.setContentAreaFilled(false);
        signupexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupexitActionPerformed(evt);
            }
        });
        signuppage.getContentPane().add(signupexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 100, 50));

        getemail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getemail.setBorder(null);
        getemail.setOpaque(false);
        signuppage.getContentPane().add(getemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 280, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup.PNG.jpg"))); // NOI18N
        jLabel5.setAlignmentX(20.0F);
        jLabel5.setAlignmentY(10.5F);
        jLabel5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel5KeyPressed(evt);
            }
        });
        signuppage.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 430));

        udpage.setLocationByPlatform(true);
        udpage.setMinimumSize(new java.awt.Dimension(777, 599));
        udpage.setUndecorated(true);
        udpage.setResizable(false);
        udpage.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.setOpaque(false);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Papyrus", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel11.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Title");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Author/Editor");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Serial Code");

        jt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Publication");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(10, 10, 10)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jt2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(jt3, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(jt4, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(jt1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(4, 4, 4)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Category", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Papyrus", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel12.setForeground(new java.awt.Color(255, 255, 255));
        jPanel12.setOpaque(false);
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup2.add(c11);
        c11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c11.setForeground(new java.awt.Color(255, 255, 255));
        c11.setText("Novel");
        c11.setOpaque(false);
        jPanel12.add(c11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        buttonGroup2.add(c12);
        c12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c12.setForeground(new java.awt.Color(255, 255, 255));
        c12.setText("Magazine");
        c12.setOpaque(false);
        jPanel12.add(c12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        buttonGroup2.add(c13);
        c13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c13.setForeground(new java.awt.Color(255, 255, 255));
        c13.setText("Newspaper");
        c13.setOpaque(false);
        jPanel12.add(c13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        buttonGroup2.add(c14);
        c14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c14.setForeground(new java.awt.Color(255, 255, 255));
        c14.setText("Comics");
        c14.setOpaque(false);
        jPanel12.add(c14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        add.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        udpage.getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 350, 340));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delete Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.setOpaque(false);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Information of a book can be removed from the database");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("only if the Serial Code of the book is known. To determine");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("the serial code, please proceed to the search page:");

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setText("Proceed to search");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Serial Code:");

        getcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getcodeActionPerformed(evt);
            }
        });

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel13.setOpaque(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Title:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Author/Editor:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Status");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Publication:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("     ");
        jLabel6.setMinimumSize(new java.awt.Dimension(40, 14));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("     ");
        jLabel7.setMinimumSize(new java.awt.Dimension(40, 14));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("     ");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("     ");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel25)
                    .addComponent(jLabel18))
                .addGap(32, 32, 32)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel19))
                .addGap(3, 3, 3)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete.setText("Delete From Database");
        delete.setEnabled(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        changestatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        changestatus.setText("Change Status");
        changestatus.setEnabled(false);
        changestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changestatusActionPerformed(evt);
            }
        });

        getinfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getinfo.setText("Get Info");
        getinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getinfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getcode, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(getinfo))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(delete)
                        .addGap(18, 18, 18)
                        .addComponent(changestatus)))
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(getcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getinfo))
                .addGap(4, 4, 4)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changestatus))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        udpage.getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 380, 340));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modify Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel10.setOpaque(false);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("MODIFY A:");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 120, -1));

        jcmb1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jcmb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Novel", "Magazine", "Newspaper", "Comic" }));
        jcmb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmb1ActionPerformed(evt);
            }
        });
        jPanel10.add(jcmb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 147, 25));

        jLabel24.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("WHOSE");
        jPanel10.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        jcmb2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jcmb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select...", "Title", "Author", "Publication", "Serial Code" }));
        jcmb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmb2ActionPerformed(evt);
            }
        });
        jPanel10.add(jcmb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 68, 147, 25));

        jLabel26.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("IS");
        jPanel10.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        btf.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jPanel10.add(btf, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 147, -1));

        jcmb3.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jcmb3.setEnabled(false);
        jPanel10.add(jcmb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 68, 147, 25));

        jLabel28.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("IS");
        jPanel10.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        ctf.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jPanel10.add(ctf, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 150, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("AND");
        jPanel10.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 38, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("AND CHANGE ITS");
        jPanel10.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 38, -1, -1));

        jcmb4.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jcmb4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Title", "Author", "Publication", "Serial Code", "Category" }));
        jPanel10.add(jcmb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 68, 163, 25));

        jLabel31.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("TO");
        jPanel10.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, -1, -1));

        dtf.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jPanel10.add(dtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 163, -1));

        modify.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        modify.setText("MODIFY MODIFY MODIFY MODIFY MODIFY MODIFY ");
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });
        jPanel10.add(modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 690, -1));

        udpage.getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 740, 220));

        signupexit1.setBorderPainted(false);
        signupexit1.setContentAreaFilled(false);
        signupexit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupexit1ActionPerformed(evt);
            }
        });
        udpage.getContentPane().add(signupexit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 220, 40));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blue.PNG.jpg"))); // NOI18N
        udpage.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 600));

        forgotpassword.setLocationByPlatform(true);
        forgotpassword.setMinimumSize(new java.awt.Dimension(583, 304));
        forgotpassword.setUndecorated(true);
        forgotpassword.setResizable(false);
        forgotpassword.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField5.setBorder(null);
        jTextField5.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField5.setOpaque(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        forgotpassword.getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 160, 20));

        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField12.setBorder(null);
        jTextField12.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField12.setOpaque(false);
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        forgotpassword.getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 160, 20));

        jButton15.setBackground(new java.awt.Color(255, 255, 255));
        jButton15.setFont(new java.awt.Font("Narkisim", 1, 24)); // NOI18N
        jButton15.setBorder(null);
        jButton15.setContentAreaFilled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        forgotpassword.getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 100, 40));

        getforgottenpass.setBackground(new java.awt.Color(255, 255, 255));
        getforgottenpass.setFont(new java.awt.Font("Narkisim", 1, 24)); // NOI18N
        getforgottenpass.setBorder(null);
        getforgottenpass.setContentAreaFilled(false);
        getforgottenpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getforgottenpassActionPerformed(evt);
            }
        });
        forgotpassword.getContentPane().add(getforgottenpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 210, 40));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forgot.jpg"))); // NOI18N
        forgotpassword.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 310));

        jOptionPane1.setMessageType(1);

        jOptionPane2.setMessageType(3);
        jOptionPane2.setOptionType(0);

        statusoption.setLocationByPlatform(true);
        statusoption.setMinimumSize(new java.awt.Dimension(379, 132));
        statusoption.setUndecorated(true);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Change Status To:");

        buttonGroup3.add(z1);
        z1.setText("Available");

        buttonGroup3.add(z3);
        z3.setText("Borrowed");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statusoptionLayout = new javax.swing.GroupLayout(statusoption.getContentPane());
        statusoption.getContentPane().setLayout(statusoptionLayout);
        statusoptionLayout.setHorizontalGroup(
            statusoptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusoptionLayout.createSequentialGroup()
                .addGroup(statusoptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusoptionLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(statusoptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(z3)
                            .addComponent(z1)))
                    .addGroup(statusoptionLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton2)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        statusoptionLayout.setVerticalGroup(
            statusoptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusoptionLayout.createSequentialGroup()
                .addGroup(statusoptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusoptionLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel21))
                    .addGroup(statusoptionLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(z1)
                        .addGap(29, 29, 29)
                        .addComponent(z3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(statusoptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        userinfo.setBackground(new java.awt.Color(0, 0, 255));
        userinfo.setForeground(new java.awt.Color(0, 0, 255));
        userinfo.setLocationByPlatform(true);
        userinfo.setMinimumSize(new java.awt.Dimension(474, 235));
        userinfo.setUndecorated(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Category", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton3.setFont(new java.awt.Font("DigifaceWide", 1, 36)); // NOI18N
        jButton3.setText("exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userinfoLayout = new javax.swing.GroupLayout(userinfo.getContentPane());
        userinfo.getContentPane().setLayout(userinfoLayout);
        userinfoLayout.setHorizontalGroup(
            userinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userinfoLayout.createSequentialGroup()
                .addGroup(userinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userinfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userinfoLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userinfoLayout.setVerticalGroup(
            userinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mumbai Vachanalay");
        setMinimumSize(new java.awt.Dimension(585, 872));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        continuebutton.setBackground(new java.awt.Color(255, 255, 255));
        continuebutton.setForeground(new java.awt.Color(255, 255, 255));
        continuebutton.setBorder(null);
        continuebutton.setBorderPainted(false);
        continuebutton.setContentAreaFilled(false);
        continuebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(continuebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 800, 370, 60));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture.PNG.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 860));

        setSize(new java.awt.Dimension(593, 886));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public String erro="ERROR!"; 
    void execute(String a,String b) throws ClassNotFoundException, SQLException
    {
    try
    {
    Class.forName("java.sql.Driver");
    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/library","root","root");
Statement stmt=conn.createStatement();
stmt.executeUpdate(a);
    stmt.close();
    conn.close();
        }
    catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,b);
        }
    }

    private void continuebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuebuttonActionPerformed
main.setVisible(true);
    }//GEN-LAST:event_continuebuttonActionPerformed

    private void opensearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opensearchActionPerformed
String x=jLabel32.getText();
if(x.equals("Not Logged In")){
    JOptionPane.showMessageDialog(null,"Please Log In First");}
else   searchpage.setVisible(true);
    }//GEN-LAST:event_opensearchActionPerformed

    private void openloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openloginActionPerformed
loginpage.setVisible(true);
    }//GEN-LAST:event_openloginActionPerformed

    private void opensignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opensignupActionPerformed
signuppage.setVisible(true);
    }//GEN-LAST:event_opensignupActionPerformed

    private void opendatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opendatabaseActionPerformed
String x=jLabel32.getText();
if(x.equals("kkadane")) udpage.setVisible(true);
else 
    JOptionPane.showMessageDialog
            (null,"Only Administraitors can use this feature");
    }//GEN-LAST:event_opendatabaseActionPerformed

    private void buttonforgotpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonforgotpassActionPerformed
forgotpassword.setVisible(true);
    }//GEN-LAST:event_buttonforgotpassActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
try{   Class.forName("java.sql.Driver");
Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/library","root","root");
Statement stmt=conn.createStatement();
String q2;
    q2 = "select * from login where username='"+getuser.getText()+"';";
ResultSet rs=stmt.executeQuery(q2);
if(!rs.next()){
    q2="select * from login where email='"+getemail.getText()+"';";
    rs=stmt.executeQuery(q2);
    if(!rs.next()){
String q="insert into login values('"+getuser.getText()+"','"+new String(getpass.getPassword())+"','"+getemail.getText()+"');";
String p="create table "+getuser.getText()+"(Title varchar(20),Category varchar(20),Status varchar(20));";
stmt.executeUpdate(q);stmt.executeUpdate(p);stmt.close(); conn.close();
JOptionPane.showMessageDialog(null,"Account Successfully Created");
signuppage.dispose();getuser.setText("");getpass.setText("");getemail.setText("");}
else{JOptionPane.showMessageDialog(null,"Email already exists!");getpass.setText("");getemail.setText("");}}
else{JOptionPane.showMessageDialog(null,"Username already exists!");
    getuser.setText("");getpass.setText("");getemail.setText("");
}
}
catch(Exception e){}

    }//GEN-LAST:event_signupActionPerformed

    private void jLabel5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5KeyPressed

    private void mainexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainexitActionPerformed
main.dispose();
    }//GEN-LAST:event_mainexitActionPerformed

    private void exitloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitloginActionPerformed
loginpage.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_exitloginActionPerformed

    private void signupexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupexitActionPerformed
signuppage.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_signupexitActionPerformed

    private void exitsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitsearchActionPerformed
searchpage.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_exitsearchActionPerformed

    private void jt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt2ActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
try{Class.forName("java.sql.Driver");
String p=new String(getpassword.getPassword());
Connection con=DriverManager.
        getConnection("jdbc:mysql://localhost/library","root","root");
Statement st=con.createStatement();
String q="select password from login where username ='"
        +getusername.getText()+"';";
ResultSet rs=st.executeQuery(q);System.out.println(q);
if(!rs.next()){JOptionPane.showMessageDialog(null,"User doesn't exist");}
else{
    do{
    String p1=rs.getString("password");
    System.out.println(p1);
    if (p1.equals(p))
{    JOptionPane.showMessageDialog(null,"Logged in Successfully");
     String namelog=getusername.getText();
      mainloginname.setText("Welcome,"+namelog);
      searchuser.setText("Welcome,"+namelog);
      jLabel32.setText(""+namelog);
      loginpage.dispose();}
 else{JOptionPane.showMessageDialog(null, "Wrong Password");}}while(rs.next());
   rs.close();st.close();con.close();
loginpage.dispose();}}

catch(Exception e){JOptionPane.showMessageDialog(null,"User not found!!");}

    }//GEN-LAST:event_loginActionPerformed

    private void getuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getuserActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_getuserActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
int n=t1.getRowCount();DefaultTableModel tm=(DefaultTableModel)t1.getModel();
for(int i=n;i>0;i--) tm.removeRow(0);
String category="";
if(c1.isSelected())category="novel";if(c2.isSelected()) category="magazine";
if(c3.isSelected())category="newspaper";if(c4.isSelected()) category="comic";
String searchby="";
if(s1.isSelected())searchby="author";if(s2.isSelected()) searchby="title";
if(s3.isSelected())searchby="publication";if(s4.isSelected()) searchby="serial";
DefaultTableModel y=(DefaultTableModel)t1.getModel();
try{Class.forName("java.sql.Driver");
Connection con=DriverManager.
        getConnection("jdbc:mysql://localhost/library","root","root");
Statement st=con.createStatement();
String q="select * from books where category='"+category+"' and "
        +searchby+" like '"+getsearchdata.getText()+"%';";
ResultSet rs=st.executeQuery(q);
while(rs.next())
{   String author=rs.getString("Author");String title=rs.getString("Title");
    String publication=rs.getString("Publication");
    String serial=rs.getString("Serial");String status=rs.getString("Status");
    y.addRow(new Object[]{author,title,publication,serial,status});}
   rs.close();st.close();con.close();
  int x=t1.getRowCount();
  if(x==0) searchresult.setText("NO RECORDS FOUND");
  else     searchresult.setText(x + " RECORDS FOUND");}
catch(Exception e){System.out.println("error in connectivity");}
    }//GEN-LAST:event_searchActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed


        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
forgotpassword.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void getforgottenpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getforgottenpassActionPerformed
try{Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection
        ("jdbc:mysql://localhost/library","root","root");
Statement st=con.createStatement();
String q="select password from login where username ='"+jTextField5.getText()+
        "' and email='"+jTextField12.getText()+"';";
ResultSet rs=st.executeQuery(q);
  while(rs.next()){   String p1=rs.getString("password");
    JOptionPane.showMessageDialog(null, "Yoir Password is "+p1);}
    rs.close();st.close();con.close(); jTextField5.setText(""); jTextField12.setText("");
forgotpassword.dispose();}
catch(Exception e){JOptionPane.showMessageDialog(null,"Wrong data entered");}
    }//GEN-LAST:event_getforgottenpassActionPerformed

    private void borrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowActionPerformed
   try{Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection
        ("jdbc:mysql://localhost/library","root","root");
Statement st=con.createStatement();
int n=Integer.parseInt(getbookcode.getText());
String q="select * from books where serial="+n+";";
ResultSet rs=st.executeQuery(q);
  while(rs.next())
{   String title=rs.getString("Title");
    String author=rs.getString("Author");
    String status=rs.getString("Status");
    String category=rs.getString("category");
showtitle.setText(""+title);
showauthor.setText(""+author);
if(status.equals("borrowed"))
{   JOptionPane.showMessageDialog(null, "The book is already borrowed!!"); }
 else{   JOptionPane.showMessageDialog(null, "Book Succcessfully Borrowed");
   String a="update books set status='borrowed' where Serial="+n+";";
   String b=jLabel32.getText();
   String c="insert into "+b+" values('"+title+"','"+category+"','borrowed');";
execute(a,erro);
execute(c,erro); 
 }
  }
    rs.close();st.close();con.close(); }
catch(Exception e) {}
    }//GEN-LAST:event_borrowActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed

    }//GEN-LAST:event_s4ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
String category="";
if(c11.isSelected()) category="novel";if(c12.isSelected()) category="magazine";
if(c13.isSelected()) category="newspaper";if(c14.isSelected()) category="comic";
String q="Insert into books values('"+jt2.getText()+"','" +jt1.getText()+"','"
          +jt3.getText()+"','"+jt4.getText()+"','available','"+category+"');";
        try {execute(q,"Error in adding record!");
            } 
        catch (Exception e) {}
    }//GEN-LAST:event_addActionPerformed

    private void signupexit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupexit1ActionPerformed
udpage.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_signupexit1ActionPerformed

    private void jcmb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmb1ActionPerformed

    }//GEN-LAST:event_jcmb1ActionPerformed

    private void jcmb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmb2ActionPerformed
String c=(String) jcmb2.getSelectedItem();
if(c.equals("Title"))
{   jcmb3.removeAllItems();jcmb3.setEnabled(true);jcmb3.addItem("Author");
    jcmb3.addItem("Publication");jcmb3.addItem("Serial");}
if(c.equals("Author"))
{   jcmb3.removeAllItems();jcmb3.setEnabled(true);jcmb3.addItem("Title");
    jcmb3.addItem("Publication"); jcmb3.addItem("Serial");}
if(c.equals("Publication"))
{   jcmb3.removeAllItems();jcmb3.setEnabled(true);jcmb3.addItem("Author");
    jcmb3.addItem("Title");jcmb3.addItem("Serial");}
if(c.equals("Serial"))
{   jcmb3.removeAllItems();jcmb3.setEnabled(true);jcmb3.addItem("Author");
    jcmb3.addItem("Title");jcmb3.addItem("Publication");}
    }//GEN-LAST:event_jcmb2ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
searchpage.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
int ans=JOptionPane.showConfirmDialog
        (null,"Are you sure you want to delete the record?");
String q="delete from books where serial="+getcode.getText()+";";
if(ans==JOptionPane.YES_OPTION)
{try{execute(q,"Unable to Delete!!");
JOptionPane.showMessageDialog(null,"Record Successfully Deleted!!");}
catch(Exception e){}}
    }//GEN-LAST:event_deleteActionPerformed

    private void getinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getinfoActionPerformed
delete.setEnabled(true);
changestatus.setEnabled(true);
try{Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection
        ("jdbc:mysql://localhost/library","root","root");
Statement st=con.createStatement();
int n=Integer.parseInt(getcode.getText());
String q="select * from books where serial="+n+";";
ResultSet rs=st.executeQuery(q);
  while(rs.next())
{String title=rs.getString("Title");String publication=rs.getString("Publication");
 String status=rs.getString("Status");String author=rs.getString("Author");
 jLabel6.setText(""+title);jLabel7.setText(""+author);
 jLabel19.setText(""+publication);jLabel20.setText(""+status);}
    rs.close();st.close();con.close(); }
catch(Exception e) { System.out.println("error in connectivity"); }
    }//GEN-LAST:event_getinfoActionPerformed

    private void changestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changestatusActionPerformed
  statusoption.setVisible(true);
    }//GEN-LAST:event_changestatusActionPerformed

    private void getcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getcodeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
statusoption.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String x="";
if(z1.isSelected()) x="available";
if(z3.isSelected()) x="borrowed";
String q="update books set status='"+x+"'where serial="+getcode.getText()+";";
try{execute(q,"Unable to change status!!");
JOptionPane.showMessageDialog(null,"Status Successfully Changed to "+x +"!!");
}
catch(Exception e)
{}
statusoption.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void getuserinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getuserinfoActionPerformed
String x=jLabel32.getText();
if( x.equals("Not Logged In"))
    JOptionPane.showMessageDialog(null,"Please Log In First");
else   {userinfo.setVisible(true);
int a=t1.getRowCount();
DefaultTableModel y=(DefaultTableModel)jTable1.getModel();
for(int i=a;i>0;i--) y.removeRow(0);

try{Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection
        ("jdbc:mysql://localhost/library","root","root");
Statement st=con.createStatement();String n=jLabel32.getText();
String q="select * from " +n+";";
ResultSet rs=st.executeQuery(q);
  while(rs.next())
{   String a1=rs.getString("Title");String a2=rs.getString("Category");
    String a3=rs.getString("Status");
y.addRow(new Object[]{a1,a2,a3});}
    rs.close();st.close();con.close();}
catch(Exception e){System.out.println("User Not Found");}}
    }//GEN-LAST:event_getuserinfoActionPerformed

    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed
String a=(String) jcmb1.getSelectedItem();
String b=(String) jcmb2.getSelectedItem();
String c=(String) jcmb3.getSelectedItem();
String d=(String) jcmb4.getSelectedItem();
String x=btf.getText();
String y=ctf.getText();
String z=dtf.getText();
String q="update books set "+d+"='"+z+"' where "+b+" like '"+x
        +"%' and "+c+" like'"+y+"%' and category='"+a+"';";
System.out.println(q);
try{execute(q,"Data Not Found");
 JOptionPane.showMessageDialog(null,"Record Successfully modified");}
catch(Exception e){}
    }//GEN-LAST:event_modifyActionPerformed

    private void mainexit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainexit1ActionPerformed
String a="create table books(Author varchar(20) not null,Title varchar(30) not null,Publication varchar(20) not null,Serial integer not null primary key unique,Status varchar(20) not null default 'available',category varchar(20) not null);";
String b="create table login(username varchar(15) not null primary key,password varchar(20) not null,email varchar(30) not null unique);";

try
{
    execute(a,erro);
    execute(b,erro);
}
catch(Exception e)
{

}
// TODO add your handling code here:
    }//GEN-LAST:event_mainexit1ActionPerformed

    private void getinfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getinfo1ActionPerformed
try{Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection
        ("jdbc:mysql://localhost/library","root","root");
Statement st=con.createStatement();
int n=Integer.parseInt(getbookcode.getText());
String q="select * from books where serial="+n+";";
ResultSet rs=st.executeQuery(q);
  while(rs.next())
{   String title=rs.getString("Title");
    String author=rs.getString("Author");
    showtitle.setText(""+title);
    showauthor.setText(""+author);}
    rs.close();
    st.close();
    con.close();
borrow.setEnabled(true);}
catch(Exception e)
{ JOptionPane.showMessageDialog(null,"Such book does'nt exist!"); }
    }//GEN-LAST:event_getinfo1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
userinfo.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
    * @param args the command line arguments
    */

public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });


}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton borrow;
    private javax.swing.JTextField btf;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton buttonforgotpass;
    private javax.swing.JRadioButton c1;
    private javax.swing.JRadioButton c11;
    private javax.swing.JRadioButton c12;
    private javax.swing.JRadioButton c13;
    private javax.swing.JRadioButton c14;
    private javax.swing.JRadioButton c2;
    private javax.swing.JRadioButton c3;
    private javax.swing.JRadioButton c4;
    private javax.swing.JButton changestatus;
    private javax.swing.JButton continuebutton;
    private javax.swing.JTextField ctf;
    private javax.swing.JButton delete;
    private javax.swing.JTextField dtf;
    private javax.swing.JButton exitlogin;
    private javax.swing.JButton exitsearch;
    private javax.swing.JFrame forgotpassword;
    private javax.swing.JTextField getbookcode;
    private javax.swing.JTextField getcode;
    private javax.swing.JTextField getemail;
    private javax.swing.JButton getforgottenpass;
    private javax.swing.JButton getinfo;
    private javax.swing.JButton getinfo1;
    private javax.swing.JPasswordField getpass;
    private javax.swing.JPasswordField getpassword;
    private javax.swing.JTextField getsearchdata;
    private javax.swing.JTextField getuser;
    private javax.swing.JButton getuserinfo;
    private javax.swing.JTextField getusername;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JOptionPane jOptionPane2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JComboBox jcmb1;
    private javax.swing.JComboBox jcmb2;
    private javax.swing.JComboBox jcmb3;
    private javax.swing.JComboBox jcmb4;
    private javax.swing.JTextField jt1;
    private javax.swing.JTextField jt2;
    private javax.swing.JTextField jt3;
    private javax.swing.JTextField jt4;
    private javax.swing.JButton login;
    private javax.swing.JFrame loginpage;
    private javax.swing.JFrame main;
    private javax.swing.JButton mainexit;
    private javax.swing.JButton mainexit1;
    private javax.swing.JLabel mainloginname;
    private javax.swing.JButton modify;
    private javax.swing.JButton opendatabase;
    private javax.swing.JButton openlogin;
    private javax.swing.JButton opensearch;
    private javax.swing.JButton opensignup;
    private javax.swing.JCheckBox rememberme;
    private javax.swing.JRadioButton s1;
    private javax.swing.JRadioButton s2;
    private javax.swing.JRadioButton s3;
    private javax.swing.JRadioButton s4;
    private javax.swing.JButton search;
    private javax.swing.JPanel searchbypanel;
    private javax.swing.JFrame searchpage;
    private javax.swing.JPanel searchpanel;
    private javax.swing.JLabel searchresult;
    private javax.swing.JLabel searchuser;
    private javax.swing.JLabel showauthor;
    private javax.swing.JLabel showtitle;
    private javax.swing.JButton signup;
    private javax.swing.JButton signupexit;
    private javax.swing.JButton signupexit1;
    private javax.swing.JFrame signuppage;
    private javax.swing.JFrame statusoption;
    private javax.swing.JTable t1;
    private javax.swing.JFrame udpage;
    private javax.swing.JFrame userinfo;
    private javax.swing.JRadioButton z1;
    private javax.swing.JRadioButton z3;
    // End of variables declaration//GEN-END:variables

}
